# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  rover:
    image: rover
    build:
      context: .
      dockerfile: Rover/Dockerfile
    ports:
      - 5000:5000
